
apiVersion: v1
kind: Service
metadata:
  name: developeriq-service
spec:
  selector:
    app: developeriq-app
  ports:
  - protocol: "TCP"
    port: 6000 #Port which kubernetes service runs on
    targetPort: 8002 #Port which the service is internally used by docker container
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developeriq-app
spec:
  selector:
    matchLabels:
      app: developeriq-app
  replicas: 5
  template:
    metadata:
      labels:
        app: developeriq-app
    spec:
      containers:
      - name: developeriq-app
        image: developer-iq-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002