version: '3'

services:
  db-update-check-service:
    build: ./
    container_name: db-update-check-service
    restart: always
    volumes:
    - ./:/DeveloperIQ/
    env_file:
      - aws_creds.env
    network_mode: host
    command: python3 DBUpdateCheckService/github_data_api.py

  db-update-service:
    build: ./
    container_name: db-update-service
    restart: always
    volumes:
    - ./:/DeveloperIQ/
    env_file:
      - aws_creds.env
    command: python3 DBUpdateService/db_update_service.py --org RasaHQ --repo rasa --delay 5
    network_mode: host
    depends_on: [db-update-check-service]
  productivity-calculation-service:
    build: ./
    container_name: productivity-calculation-service
    restart: always
    ports:
    - 8002:8002
    volumes:
    - ./:/DeveloperIQ/
    env_file:
      - aws_creds.env
    command: python3 ProductivityCalculationService/productivity_calculation_service.py
    depends_on: [db-update-service]



