
from typing import List, Optional, Set, Dict
sample = [{
    "w": 1614470400,
    "a": 0,
    "d": 0,
    "c": 4
},
{
    "w": 1615075200,
    "a": 0,
    "d": 0,
    "c": 4
},
{
    "w": 1615680000,
    "a": 0,
    "d": 0,
    "c": 4
},
{
    "w": 1616284800,
    "a": 0,
    "d": 0,
    "c": 2
},
{
    "w": 1616889600,
    "a": 0,
    "d": 0,
    "c": 3
},
{
    "w": 1617494400,
    "a": 0,
    "d": 0,
    "c": 5
},
{
    "w": 1618099200,
    "a": 0,
    "d": 0,
    "c": 5
}]

def calculate_commit_contribution(contribution_lst:List):
    total_additions = 0
    total_deletions = 0
    total_commits   = 0
    print(range(len(contribution_lst)))
    for contribution_idx in range(len(contribution_lst)+1):
            print("HOP : " ,contribution_idx)
            if contribution_idx != 0:
                total_additions += contribution_lst[contribution_idx-1]["a"]
                total_deletions += contribution_lst[contribution_idx-1]["d"]
                total_commits   += contribution_lst[contribution_idx-1]["c"]

                print("t commit",total_commits)
                print("t addition",total_additions)
                print("t deletiion",total_deletions)

                print("curr_commit : " , contribution_lst[contribution_idx-1]["c"])
                print("curr_deletion : ", contribution_lst[contribution_idx - 1]["d"])
                print("curr_addition : ", contribution_lst[contribution_idx - 1]["a"])

    total_contribution = {
                    "additions":total_additions,
                    "deletions":total_deletions,
                    "number_of_commits":total_commits
    }
    return total_contribution

sample_inp = sample[-4:]
total_contrib = calculate_commit_contribution(sample_inp)
print(total_contrib)

x_2 = [
    {
        "login": "tmbo",
        "id": 1098412,
        "node_id": "MDQ6VXNlcjEwOTg0MTI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1098412?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tmbo",
        "html_url": "https://github.com/tmbo",
        "followers_url": "https://api.github.com/users/tmbo/followers",
        "following_url": "https://api.github.com/users/tmbo/following{/other_user}",
        "gists_url": "https://api.github.com/users/tmbo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tmbo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tmbo/subscriptions",
        "organizations_url": "https://api.github.com/users/tmbo/orgs",
        "repos_url": "https://api.github.com/users/tmbo/repos",
        "events_url": "https://api.github.com/users/tmbo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tmbo/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 3704
    },
    {
        "login": "wochinge",
        "id": 7667273,
        "node_id": "MDQ6VXNlcjc2NjcyNzM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7667273?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/wochinge",
        "html_url": "https://github.com/wochinge",
        "followers_url": "https://api.github.com/users/wochinge/followers",
        "following_url": "https://api.github.com/users/wochinge/following{/other_user}",
        "gists_url": "https://api.github.com/users/wochinge/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/wochinge/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wochinge/subscriptions",
        "organizations_url": "https://api.github.com/users/wochinge/orgs",
        "repos_url": "https://api.github.com/users/wochinge/repos",
        "events_url": "https://api.github.com/users/wochinge/events{/privacy}",
        "received_events_url": "https://api.github.com/users/wochinge/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 2374
    },
    {
        "login": "tabergma",
        "id": 7203823,
        "node_id": "MDQ6VXNlcjcyMDM4MjM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7203823?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tabergma",
        "html_url": "https://github.com/tabergma",
        "followers_url": "https://api.github.com/users/tabergma/followers",
        "following_url": "https://api.github.com/users/tabergma/following{/other_user}",
        "gists_url": "https://api.github.com/users/tabergma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tabergma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tabergma/subscriptions",
        "organizations_url": "https://api.github.com/users/tabergma/orgs",
        "repos_url": "https://api.github.com/users/tabergma/repos",
        "events_url": "https://api.github.com/users/tabergma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tabergma/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 2256
    },
    {
        "login": "Ghostvv",
        "id": 4136956,
        "node_id": "MDQ6VXNlcjQxMzY5NTY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/4136956?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Ghostvv",
        "html_url": "https://github.com/Ghostvv",
        "followers_url": "https://api.github.com/users/Ghostvv/followers",
        "following_url": "https://api.github.com/users/Ghostvv/following{/other_user}",
        "gists_url": "https://api.github.com/users/Ghostvv/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Ghostvv/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Ghostvv/subscriptions",
        "organizations_url": "https://api.github.com/users/Ghostvv/orgs",
        "repos_url": "https://api.github.com/users/Ghostvv/repos",
        "events_url": "https://api.github.com/users/Ghostvv/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Ghostvv/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 1806
    },
    {
        "login": "ricwo",
        "id": 20581300,
        "node_id": "MDQ6VXNlcjIwNTgxMzAw",
        "avatar_url": "https://avatars.githubusercontent.com/u/20581300?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ricwo",
        "html_url": "https://github.com/ricwo",
        "followers_url": "https://api.github.com/users/ricwo/followers",
        "following_url": "https://api.github.com/users/ricwo/following{/other_user}",
        "gists_url": "https://api.github.com/users/ricwo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ricwo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ricwo/subscriptions",
        "organizations_url": "https://api.github.com/users/ricwo/orgs",
        "repos_url": "https://api.github.com/users/ricwo/repos",
        "events_url": "https://api.github.com/users/ricwo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ricwo/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 1333
    },
    {
        "login": "erohmensing",
        "id": 22333512,
        "node_id": "MDQ6VXNlcjIyMzMzNTEy",
        "avatar_url": "https://avatars.githubusercontent.com/u/22333512?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/erohmensing",
        "html_url": "https://github.com/erohmensing",
        "followers_url": "https://api.github.com/users/erohmensing/followers",
        "following_url": "https://api.github.com/users/erohmensing/following{/other_user}",
        "gists_url": "https://api.github.com/users/erohmensing/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/erohmensing/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/erohmensing/subscriptions",
        "organizations_url": "https://api.github.com/users/erohmensing/orgs",
        "repos_url": "https://api.github.com/users/erohmensing/repos",
        "events_url": "https://api.github.com/users/erohmensing/events{/privacy}",
        "received_events_url": "https://api.github.com/users/erohmensing/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 1222
    },
    {
        "login": "amn41",
        "id": 5114084,
        "node_id": "MDQ6VXNlcjUxMTQwODQ=",
        "avatar_url": "https://avatars.githubusercontent.com/u/5114084?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/amn41",
        "html_url": "https://github.com/amn41",
        "followers_url": "https://api.github.com/users/amn41/followers",
        "following_url": "https://api.github.com/users/amn41/following{/other_user}",
        "gists_url": "https://api.github.com/users/amn41/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/amn41/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/amn41/subscriptions",
        "organizations_url": "https://api.github.com/users/amn41/orgs",
        "repos_url": "https://api.github.com/users/amn41/repos",
        "events_url": "https://api.github.com/users/amn41/events{/privacy}",
        "received_events_url": "https://api.github.com/users/amn41/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 1143
    },
    {
        "login": "rasabot",
        "id": 43567378,
        "node_id": "MDQ6VXNlcjQzNTY3Mzc4",
        "avatar_url": "https://avatars.githubusercontent.com/u/43567378?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rasabot",
        "html_url": "https://github.com/rasabot",
        "followers_url": "https://api.github.com/users/rasabot/followers",
        "following_url": "https://api.github.com/users/rasabot/following{/other_user}",
        "gists_url": "https://api.github.com/users/rasabot/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rasabot/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rasabot/subscriptions",
        "organizations_url": "https://api.github.com/users/rasabot/orgs",
        "repos_url": "https://api.github.com/users/rasabot/repos",
        "events_url": "https://api.github.com/users/rasabot/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rasabot/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 1055
    },
    {
        "login": "akelad",
        "id": 32450038,
        "node_id": "MDQ6VXNlcjMyNDUwMDM4",
        "avatar_url": "https://avatars.githubusercontent.com/u/32450038?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/akelad",
        "html_url": "https://github.com/akelad",
        "followers_url": "https://api.github.com/users/akelad/followers",
        "following_url": "https://api.github.com/users/akelad/following{/other_user}",
        "gists_url": "https://api.github.com/users/akelad/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/akelad/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/akelad/subscriptions",
        "organizations_url": "https://api.github.com/users/akelad/orgs",
        "repos_url": "https://api.github.com/users/akelad/repos",
        "events_url": "https://api.github.com/users/akelad/events{/privacy}",
        "received_events_url": "https://api.github.com/users/akelad/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 791
    },
    {
        "login": "m-vdb",
        "id": 1931615,
        "node_id": "MDQ6VXNlcjE5MzE2MTU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1931615?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/m-vdb",
        "html_url": "https://github.com/m-vdb",
        "followers_url": "https://api.github.com/users/m-vdb/followers",
        "following_url": "https://api.github.com/users/m-vdb/following{/other_user}",
        "gists_url": "https://api.github.com/users/m-vdb/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/m-vdb/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/m-vdb/subscriptions",
        "organizations_url": "https://api.github.com/users/m-vdb/orgs",
        "repos_url": "https://api.github.com/users/m-vdb/repos",
        "events_url": "https://api.github.com/users/m-vdb/events{/privacy}",
        "received_events_url": "https://api.github.com/users/m-vdb/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 782
    },
    {
        "login": "dakshvar22",
        "id": 8708249,
        "node_id": "MDQ6VXNlcjg3MDgyNDk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8708249?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dakshvar22",
        "html_url": "https://github.com/dakshvar22",
        "followers_url": "https://api.github.com/users/dakshvar22/followers",
        "following_url": "https://api.github.com/users/dakshvar22/following{/other_user}",
        "gists_url": "https://api.github.com/users/dakshvar22/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dakshvar22/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dakshvar22/subscriptions",
        "organizations_url": "https://api.github.com/users/dakshvar22/orgs",
        "repos_url": "https://api.github.com/users/dakshvar22/repos",
        "events_url": "https://api.github.com/users/dakshvar22/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dakshvar22/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 733
    },
    {
        "login": "alwx",
        "id": 911127,
        "node_id": "MDQ6VXNlcjkxMTEyNw==",
        "avatar_url": "https://avatars.githubusercontent.com/u/911127?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/alwx",
        "html_url": "https://github.com/alwx",
        "followers_url": "https://api.github.com/users/alwx/followers",
        "following_url": "https://api.github.com/users/alwx/following{/other_user}",
        "gists_url": "https://api.github.com/users/alwx/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/alwx/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/alwx/subscriptions",
        "organizations_url": "https://api.github.com/users/alwx/orgs",
        "repos_url": "https://api.github.com/users/alwx/repos",
        "events_url": "https://api.github.com/users/alwx/events{/privacy}",
        "received_events_url": "https://api.github.com/users/alwx/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 585
    },
    {
        "login": "MetcalfeTom",
        "id": 35203669,
        "node_id": "MDQ6VXNlcjM1MjAzNjY5",
        "avatar_url": "https://avatars.githubusercontent.com/u/35203669?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MetcalfeTom",
        "html_url": "https://github.com/MetcalfeTom",
        "followers_url": "https://api.github.com/users/MetcalfeTom/followers",
        "following_url": "https://api.github.com/users/MetcalfeTom/following{/other_user}",
        "gists_url": "https://api.github.com/users/MetcalfeTom/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MetcalfeTom/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MetcalfeTom/subscriptions",
        "organizations_url": "https://api.github.com/users/MetcalfeTom/orgs",
        "repos_url": "https://api.github.com/users/MetcalfeTom/repos",
        "events_url": "https://api.github.com/users/MetcalfeTom/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MetcalfeTom/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 514
    },
    {
        "login": "imLew",
        "id": 24591179,
        "node_id": "MDQ6VXNlcjI0NTkxMTc5",
        "avatar_url": "https://avatars.githubusercontent.com/u/24591179?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/imLew",
        "html_url": "https://github.com/imLew",
        "followers_url": "https://api.github.com/users/imLew/followers",
        "following_url": "https://api.github.com/users/imLew/following{/other_user}",
        "gists_url": "https://api.github.com/users/imLew/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/imLew/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/imLew/subscriptions",
        "organizations_url": "https://api.github.com/users/imLew/orgs",
        "repos_url": "https://api.github.com/users/imLew/repos",
        "events_url": "https://api.github.com/users/imLew/events{/privacy}",
        "received_events_url": "https://api.github.com/users/imLew/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 406
    },
    {
        "login": "melindaloubser1",
        "id": 32034278,
        "node_id": "MDQ6VXNlcjMyMDM0Mjc4",
        "avatar_url": "https://avatars.githubusercontent.com/u/32034278?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/melindaloubser1",
        "html_url": "https://github.com/melindaloubser1",
        "followers_url": "https://api.github.com/users/melindaloubser1/followers",
        "following_url": "https://api.github.com/users/melindaloubser1/following{/other_user}",
        "gists_url": "https://api.github.com/users/melindaloubser1/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/melindaloubser1/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/melindaloubser1/subscriptions",
        "organizations_url": "https://api.github.com/users/melindaloubser1/orgs",
        "repos_url": "https://api.github.com/users/melindaloubser1/repos",
        "events_url": "https://api.github.com/users/melindaloubser1/events{/privacy}",
        "received_events_url": "https://api.github.com/users/melindaloubser1/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 373
    },
    {
        "login": "JEM-Mosig",
        "id": 31377126,
        "node_id": "MDQ6VXNlcjMxMzc3MTI2",
        "avatar_url": "https://avatars.githubusercontent.com/u/31377126?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/JEM-Mosig",
        "html_url": "https://github.com/JEM-Mosig",
        "followers_url": "https://api.github.com/users/JEM-Mosig/followers",
        "following_url": "https://api.github.com/users/JEM-Mosig/following{/other_user}",
        "gists_url": "https://api.github.com/users/JEM-Mosig/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/JEM-Mosig/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/JEM-Mosig/subscriptions",
        "organizations_url": "https://api.github.com/users/JEM-Mosig/orgs",
        "repos_url": "https://api.github.com/users/JEM-Mosig/repos",
        "events_url": "https://api.github.com/users/JEM-Mosig/events{/privacy}",
        "received_events_url": "https://api.github.com/users/JEM-Mosig/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 315
    },
    {
        "login": "federicotdn",
        "id": 6868935,
        "node_id": "MDQ6VXNlcjY4Njg5MzU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6868935?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/federicotdn",
        "html_url": "https://github.com/federicotdn",
        "followers_url": "https://api.github.com/users/federicotdn/followers",
        "following_url": "https://api.github.com/users/federicotdn/following{/other_user}",
        "gists_url": "https://api.github.com/users/federicotdn/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/federicotdn/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/federicotdn/subscriptions",
        "organizations_url": "https://api.github.com/users/federicotdn/orgs",
        "repos_url": "https://api.github.com/users/federicotdn/repos",
        "events_url": "https://api.github.com/users/federicotdn/events{/privacy}",
        "received_events_url": "https://api.github.com/users/federicotdn/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 276
    },
    {
        "login": "b-quachtran",
        "id": 65514514,
        "node_id": "MDQ6VXNlcjY1NTE0NTE0",
        "avatar_url": "https://avatars.githubusercontent.com/u/65514514?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/b-quachtran",
        "html_url": "https://github.com/b-quachtran",
        "followers_url": "https://api.github.com/users/b-quachtran/followers",
        "following_url": "https://api.github.com/users/b-quachtran/following{/other_user}",
        "gists_url": "https://api.github.com/users/b-quachtran/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/b-quachtran/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/b-quachtran/subscriptions",
        "organizations_url": "https://api.github.com/users/b-quachtran/orgs",
        "repos_url": "https://api.github.com/users/b-quachtran/repos",
        "events_url": "https://api.github.com/users/b-quachtran/events{/privacy}",
        "received_events_url": "https://api.github.com/users/b-quachtran/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 245
    },
    {
        "login": "evgeniiaraz",
        "id": 17569280,
        "node_id": "MDQ6VXNlcjE3NTY5Mjgw",
        "avatar_url": "https://avatars.githubusercontent.com/u/17569280?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/evgeniiaraz",
        "html_url": "https://github.com/evgeniiaraz",
        "followers_url": "https://api.github.com/users/evgeniiaraz/followers",
        "following_url": "https://api.github.com/users/evgeniiaraz/following{/other_user}",
        "gists_url": "https://api.github.com/users/evgeniiaraz/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/evgeniiaraz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/evgeniiaraz/subscriptions",
        "organizations_url": "https://api.github.com/users/evgeniiaraz/orgs",
        "repos_url": "https://api.github.com/users/evgeniiaraz/repos",
        "events_url": "https://api.github.com/users/evgeniiaraz/events{/privacy}",
        "received_events_url": "https://api.github.com/users/evgeniiaraz/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 232
    },
    {
        "login": "tczekajlo",
        "id": 7704257,
        "node_id": "MDQ6VXNlcjc3MDQyNTc=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7704257?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tczekajlo",
        "html_url": "https://github.com/tczekajlo",
        "followers_url": "https://api.github.com/users/tczekajlo/followers",
        "following_url": "https://api.github.com/users/tczekajlo/following{/other_user}",
        "gists_url": "https://api.github.com/users/tczekajlo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tczekajlo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tczekajlo/subscriptions",
        "organizations_url": "https://api.github.com/users/tczekajlo/orgs",
        "repos_url": "https://api.github.com/users/tczekajlo/repos",
        "events_url": "https://api.github.com/users/tczekajlo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tczekajlo/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 231
    },
    {
        "login": "degiz",
        "id": 2385290,
        "node_id": "MDQ6VXNlcjIzODUyOTA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/2385290?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/degiz",
        "html_url": "https://github.com/degiz",
        "followers_url": "https://api.github.com/users/degiz/followers",
        "following_url": "https://api.github.com/users/degiz/following{/other_user}",
        "gists_url": "https://api.github.com/users/degiz/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/degiz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/degiz/subscriptions",
        "organizations_url": "https://api.github.com/users/degiz/orgs",
        "repos_url": "https://api.github.com/users/degiz/repos",
        "events_url": "https://api.github.com/users/degiz/events{/privacy}",
        "received_events_url": "https://api.github.com/users/degiz/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 221
    },
    {
        "login": "msamogh",
        "id": 1230386,
        "node_id": "MDQ6VXNlcjEyMzAzODY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1230386?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/msamogh",
        "html_url": "https://github.com/msamogh",
        "followers_url": "https://api.github.com/users/msamogh/followers",
        "following_url": "https://api.github.com/users/msamogh/following{/other_user}",
        "gists_url": "https://api.github.com/users/msamogh/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/msamogh/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/msamogh/subscriptions",
        "organizations_url": "https://api.github.com/users/msamogh/orgs",
        "repos_url": "https://api.github.com/users/msamogh/repos",
        "events_url": "https://api.github.com/users/msamogh/events{/privacy}",
        "received_events_url": "https://api.github.com/users/msamogh/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 218
    },
    {
        "login": "koaning",
        "id": 1019791,
        "node_id": "MDQ6VXNlcjEwMTk3OTE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1019791?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/koaning",
        "html_url": "https://github.com/koaning",
        "followers_url": "https://api.github.com/users/koaning/followers",
        "following_url": "https://api.github.com/users/koaning/following{/other_user}",
        "gists_url": "https://api.github.com/users/koaning/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/koaning/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/koaning/subscriptions",
        "organizations_url": "https://api.github.com/users/koaning/orgs",
        "repos_url": "https://api.github.com/users/koaning/repos",
        "events_url": "https://api.github.com/users/koaning/events{/privacy}",
        "received_events_url": "https://api.github.com/users/koaning/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 168
    },
    {
        "login": "koernerfelicia",
        "id": 45405119,
        "node_id": "MDQ6VXNlcjQ1NDA1MTE5",
        "avatar_url": "https://avatars.githubusercontent.com/u/45405119?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/koernerfelicia",
        "html_url": "https://github.com/koernerfelicia",
        "followers_url": "https://api.github.com/users/koernerfelicia/followers",
        "following_url": "https://api.github.com/users/koernerfelicia/following{/other_user}",
        "gists_url": "https://api.github.com/users/koernerfelicia/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/koernerfelicia/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/koernerfelicia/subscriptions",
        "organizations_url": "https://api.github.com/users/koernerfelicia/orgs",
        "repos_url": "https://api.github.com/users/koernerfelicia/repos",
        "events_url": "https://api.github.com/users/koernerfelicia/events{/privacy}",
        "received_events_url": "https://api.github.com/users/koernerfelicia/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 151
    },
    {
        "login": "chkoss",
        "id": 38207117,
        "node_id": "MDQ6VXNlcjM4MjA3MTE3",
        "avatar_url": "https://avatars.githubusercontent.com/u/38207117?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chkoss",
        "html_url": "https://github.com/chkoss",
        "followers_url": "https://api.github.com/users/chkoss/followers",
        "following_url": "https://api.github.com/users/chkoss/following{/other_user}",
        "gists_url": "https://api.github.com/users/chkoss/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/chkoss/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/chkoss/subscriptions",
        "organizations_url": "https://api.github.com/users/chkoss/orgs",
        "repos_url": "https://api.github.com/users/chkoss/repos",
        "events_url": "https://api.github.com/users/chkoss/events{/privacy}",
        "received_events_url": "https://api.github.com/users/chkoss/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 135
    },
    {
        "login": "howl-anderson",
        "id": 1263428,
        "node_id": "MDQ6VXNlcjEyNjM0Mjg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1263428?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/howl-anderson",
        "html_url": "https://github.com/howl-anderson",
        "followers_url": "https://api.github.com/users/howl-anderson/followers",
        "following_url": "https://api.github.com/users/howl-anderson/following{/other_user}",
        "gists_url": "https://api.github.com/users/howl-anderson/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/howl-anderson/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/howl-anderson/subscriptions",
        "organizations_url": "https://api.github.com/users/howl-anderson/orgs",
        "repos_url": "https://api.github.com/users/howl-anderson/repos",
        "events_url": "https://api.github.com/users/howl-anderson/events{/privacy}",
        "received_events_url": "https://api.github.com/users/howl-anderson/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 130
    },
    {
        "login": "tttthomasssss",
        "id": 480884,
        "node_id": "MDQ6VXNlcjQ4MDg4NA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/480884?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tttthomasssss",
        "html_url": "https://github.com/tttthomasssss",
        "followers_url": "https://api.github.com/users/tttthomasssss/followers",
        "following_url": "https://api.github.com/users/tttthomasssss/following{/other_user}",
        "gists_url": "https://api.github.com/users/tttthomasssss/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tttthomasssss/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tttthomasssss/subscriptions",
        "organizations_url": "https://api.github.com/users/tttthomasssss/orgs",
        "repos_url": "https://api.github.com/users/tttthomasssss/repos",
        "events_url": "https://api.github.com/users/tttthomasssss/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tttthomasssss/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 124
    },
    {
        "login": "PHLF",
        "id": 10827301,
        "node_id": "MDQ6VXNlcjEwODI3MzAx",
        "avatar_url": "https://avatars.githubusercontent.com/u/10827301?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/PHLF",
        "html_url": "https://github.com/PHLF",
        "followers_url": "https://api.github.com/users/PHLF/followers",
        "following_url": "https://api.github.com/users/PHLF/following{/other_user}",
        "gists_url": "https://api.github.com/users/PHLF/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/PHLF/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/PHLF/subscriptions",
        "organizations_url": "https://api.github.com/users/PHLF/orgs",
        "repos_url": "https://api.github.com/users/PHLF/repos",
        "events_url": "https://api.github.com/users/PHLF/events{/privacy}",
        "received_events_url": "https://api.github.com/users/PHLF/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 116
    },
    {
        "login": "twerkmeister",
        "id": 1107341,
        "node_id": "MDQ6VXNlcjExMDczNDE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1107341?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/twerkmeister",
        "html_url": "https://github.com/twerkmeister",
        "followers_url": "https://api.github.com/users/twerkmeister/followers",
        "following_url": "https://api.github.com/users/twerkmeister/following{/other_user}",
        "gists_url": "https://api.github.com/users/twerkmeister/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/twerkmeister/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/twerkmeister/subscriptions",
        "organizations_url": "https://api.github.com/users/twerkmeister/orgs",
        "repos_url": "https://api.github.com/users/twerkmeister/repos",
        "events_url": "https://api.github.com/users/twerkmeister/events{/privacy}",
        "received_events_url": "https://api.github.com/users/twerkmeister/received_events",
        "type": "User",
        "site_admin": False
        ,
        "contributions": 114
    },
    {
        "login": "EPedrotti",
        "id": 44090731,
        "node_id": "MDQ6VXNlcjQ0MDkwNzMx",
        "avatar_url": "https://avatars.githubusercontent.com/u/44090731?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/EPedrotti",
        "html_url": "https://github.com/EPedrotti",
        "followers_url": "https://api.github.com/users/EPedrotti/followers",
        "following_url": "https://api.github.com/users/EPedrotti/following{/other_user}",
        "gists_url": "https://api.github.com/users/EPedrotti/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/EPedrotti/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/EPedrotti/subscriptions",
        "organizations_url": "https://api.github.com/users/EPedrotti/orgs",
        "repos_url": "https://api.github.com/users/EPedrotti/repos",
        "events_url": "https://api.github.com/users/EPedrotti/events{/privacy}",
        "received_events_url": "https://api.github.com/users/EPedrotti/received_events",
        "type": "User",
        "site_admin": False,
        "contributions": 106
    }
]

print("TOTAL CONTRIBUTORS: ",len(x_2))